services:
  - type: web
    name: manimations-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: manimations-db
          property: connectionString
    
databases:
  - name: manimations-db
    databaseName: manimations
    user: manimations